improve robustness of starting/stopping. Each PID file now contains host name in its name (not in its contents) so it's simpler to check for existing services running on a host. Also it means same FS can be used to start same service on different VMs (scaling horizontally).

diff --git a/deployments/src/main/distros/rest/bin/start b/deployments/src/main/distros/rest/bin/start
--- a/deployments/src/main/distros/rest/bin/start
+++ b/deployments/src/main/distros/rest/bin/start
@@ -18,7 +18,7 @@ PERMITTED_USER="uni_qgo,uni_adm,eddturner"
 SERVICE_PATH="$(pwd -P)"
 RUN_DIR="$SERVICE_PATH/out"
 LIB_DIR="$SERVICE_PATH/lib"
-PIDFILE="$RUN_DIR/run.pid"
+PIDFILE="$RUN_DIR/up@$(hostname).pid"
 SERVICE_JAR="$ARTIFACT_ID-$ARTIFACT_VERSION.jar"
 SERVER_ADDR_BINDING="-Dserver.address=0.0.0.0"
 SERVER_PORT="-Dserver.port=$PORT"
@@ -33,7 +33,22 @@ if ! echo "$PERMITTED_USER" | grep "$USER" > /dev/null 2>&1; then
     exit 1;
 fi;
 
+# ======= if a PID file exists, it looks as though the service has already been started =======================================
+if [ -e $PIDFILE ]
+then
+    # ======= read PIDFILE to check the PID =======================================
+    PIDSTR=$(cat $PIDFILE)
 
+    if ps "$PIDSTR" > /dev/null; then
+        # ======= PID exists so do not proceed =======================================
+        echo "Service is already running (see PID $PIDSTR). Please stop it before trying to start it."
+        exit 1
+    else
+        # ======= PID does not exist so remove invalid PID file =======================================
+        echo "No PID $PIDSTR on host, $(hostname) found. Removing invalid PID file, $PIDFILE."
+        rm $PIDFILE
+    fi
+fi
 
 [ ! -z "$ARTIFACT_GROUP" ] || [ ! -z "$ARTIFACT_VERSION" ] || [[ ! -z "$ARTIFACT_ID" ]] || {
     echo "Please specify the environment variables ARTIFACT_GROUP, ARTIFACT_VERSION and ARTIFACT_ID, in file, \
@@ -67,12 +82,7 @@ fi
 # ======= build the command to start the service =======================================
 RUN_COMMAND="$JAVA $JVM_MEM_MIN $JVM_MEM_MAX $JAVA_OPTS $SERVER_PORT $SPRING_LOADER_PATH $SERVER_ADDR_BINDING -jar $LIB_DIR/$SERVICE_JAR $SPRING_CONFIG_LOCATION"
 
-# ======= bail if the service has already been started =======================================
-if [ -e $PIDFILE ]
-then
-    echo "Service has already been started: $(cat $PIDFILE)"
-    exit 1
-fi
+
 
 # ======= save current directory =======================================
 pushd . > /dev/null
@@ -110,6 +120,6 @@ ps $PID > /dev/null || {
 popd > /dev/null
 
 echo "PID retrieved successfully"
-echo "$PID $(hostname)" > $PIDFILE
+echo "$PID" > $PIDFILE
 
-echo "Service was started with PID, $PID, on host, $(hostname)"
+echo "Service has now been started with PID, $PID, on host, $(hostname)"
diff --git a/deployments/src/main/distros/rest/bin/stop b/deployments/src/main/distros/rest/bin/stop
--- a/deployments/src/main/distros/rest/bin/stop
+++ b/deployments/src/main/distros/rest/bin/stop
@@ -25,33 +25,32 @@ fi;
 # ======= variables to ID service =======================================
 SERVICE_PATH="$(pwd -P)"
 RUN_DIR="$SERVICE_PATH/out"
-PIDFILE="$RUN_DIR/run.pid"
+PIDFILE="$RUN_DIR/up@$(hostname).pid"
 
 # ======= no PID file existence indicates the service is not running =======================================
 if [ ! -f $PIDFILE ]
 then
-    echo "Warning: PID file does not exist. Please check if the service is running."
+    echo "Warning: PID file does not exist ($PIDFILE). Please check if the service is running."
     exit 1;
 fi
 
-# ======= read PIDFILE to check the hostname =======================================
+# ======= read PIDFILE to check the PID =======================================
 PIDSTR=$(cat $PIDFILE)
-read -ra PIDFILE_ARRAY <<<"$PIDSTR"
 
-if [ ${PIDFILE_ARRAY[1]} != $(hostname) ]
-then
-    echo "Current host: $(hostname), PID host: ${PIDFILE_ARRAY[1]} "
-    echo "This 'stop' command needs to be run on the same host it was started on."
-    exit 1
+if ps "$PIDSTR" > /dev/null; then
+    # ======= stop the application =======================================
+    echo "Stopping the job with PID: $PIDSTR."
+    kill $PIDSTR > /dev/null 2>&1 || {
+        echo "Could not kill process. Please check the PID manually: $PIDSTR"
+        exit 1;
+    }
+else
+   echo "No PID $PIDSTR on host, $(hostname) found. Nothing to stop."
 fi
 
-# ======= stop the application =======================================
-echo "Stopping the job with PID: ${PIDFILE_ARRAY[0]}."
-kill ${PIDFILE_ARRAY[0]} > /dev/null 2>&1 || {
-    echo "Could not kill process. Please check the PID manually: ${PIDFILE_ARRAY[0]}"
-    exit 1;
-}
-
+# ======= remove the now invalid PID file =======================================
+echo "Removing the now old PID file $PIDFILE"
 rm $PIDFILE
 
-echo "Stopped."
+
+echo "The service $PIDSTR is no longer running."
