implement prepare-index-create for profiles

diff --git a/deployments/src/main/distros/index/bin/prepare-index-create b/deployments/src/main/distros/index/bin/prepare-index-create
--- a/deployments/src/main/distros/index/bin/prepare-index-create
+++ b/deployments/src/main/distros/index/bin/prepare-index-create
@@ -1,12 +1,24 @@
-#!/bin/bash
+#! /bin/bash
 
-#fail on error
+# fail on error
 set -e
 
-VALID_USERS=("uni_qgo");
+VALID_USERS=("uni_qgo" "eddturner");
 RELEASE_VERSION_PREFIX="v";
 
-nextReleaseVersion (){
+## ---------------------------- UTILITY FUNCTIONS ----------------------------
+function showHelp {
+    cat<<EOF
+Usage: $0 profile
+
+Argument description:
+  profile    =>    the profile for which we want to create a new set of Solr configuration files and data-set
+
+  Example: $0 dev
+EOF
+}
+
+function nextReleaseVersion {
    current_release="$(ls $release_dir | sed "s/${RELEASE_VERSION_PREFIX}//g" | sort -n | tail -1)";
 
    if [ ! -z "$current_release" ]; then
@@ -16,33 +28,30 @@ nextReleaseVersion (){
    fi
 }
 
-# read common environment variables
-properties_not_found="false";
-
-source "../common/common.variables";
-
-if [ $? -eq 1 ]; then
-    properties_not_found="true";
-fi
-
-source "index.variables";
-if [ $? -eq 1 ]; then
-    properties_not_found="true";
-fi
-
-source "../common/lsf.command.variables";
-if [ $? -eq 1 ]; then
-    properties_not_found="true";
-fi
-
-if [ "$properties_not_found" = "true" ]; then
+# ------------------------ SOURCE NECESSARY FILES ------------------------
+if ! source "../common/common" || ! source "../common/common.variables" || ! source "index.variables" || ! source "../common/lsf.command.variables"; then
     echo "Required properties files were not found. Please make sure you're in the right directory";
     exit 1;
 fi
 
-# ------------------------ abort if we're building in a staging environment ------------------------
-if [ "$vm_purpose" == "STAGE" ] ; then
-    prettyEcho "QuickGO <bold>build related tasks</bold> should not take place in a <bold>STAGING</bold> environment";
+# ------------------------ VALIDATE PARAMETERS ------------------------
+if [ $# -ne 1 ]; then
+    showHelp;
+    exit 1;
+fi
+requestedProfile="$1"
+
+# check core is correct
+if ! isValidProfileId "$CORE_NAME"; then
+    prettyEcho "<error>Invalid core name: $CORE_NAME.
+                    Please check your index.variables and vm-profiles.properties file.</error>";
+    exit 1;
+fi
+
+# check profile specified is correct
+if ! isValidProfileId "$CORE_NAME" "$requestedProfile"; then
+    prettyEcho "<error>Invalid profile name: $requestedProfile.
+                    Please check your index.variables and vm-profiles.properties file.</error>";
     exit 1;
 fi
 
@@ -53,17 +62,17 @@ if [ -z "$SOLR_ADDRESS" ]; then
 fi
 
 # ------------------------ start off the indexing via LSF ------------------------
-release_dir="${SOLR_INDEX_DIR}/${CORE_NAME}";
+release_dir="${SOLR_INDEX_DIR}/${CORE_NAME}/${requestedProfile}";
 
 if [ ! -d "$release_dir" ]; then
    echo "Directory for storing solr-indexes [${release_dir}] NOT FOUND. Creating...";
    mkdir -p "$release_dir";
 fi
 
-#calculate the next release for the current $release_dir
+# calculate the next release for the current $release_dir
 nextReleaseVersion;
 
-#create dir for current release
+# create dir for current release
 release_dir="${release_dir}/${next_release}/conf";
 mkdir -p "$release_dir";
 
@@ -73,11 +82,9 @@ echo "executing fetch-libraries"
 echo "executing fetch-cores"
 ../fetch-cores "$release_dir";
 
-#check solr server status
-server_status="$(solrServerStatus)";
-
-if [ "$server_status" == "UP" ]; then
-    echo "Solr server is currently UP, please restart the server, before proceeding to index-create";
+# check solr server statuses
+if allServersUpForCoreProfile "$CORE_NAME" "$requestedProfile"; then
+    echo "All solr servers for $CORE_NAME|$requestedProfile are currently UP, please restart them, before proceeding to index-create";
 else
     echo "Preparation to create index DONE."
     echo "Proceed to index-create to submit indexing job";
