comments and tidying for startup

diff --git a/ontology-rest/src/main/bin/start b/ontology-rest/src/main/bin/start
--- a/ontology-rest/src/main/bin/start
+++ b/ontology-rest/src/main/bin/start
@@ -1,37 +1,78 @@
 #! /bin/bash
 
+##=========================================================================================
+# Starts the self-contained web-application
+##=========================================================================================
+
 set -euo pipefail
 IFS=$'\n\t '
 
-# check the right user runs this
-if [ $USER != "eddturner" ] ; then
+# ======= CONSTANTS =======================================
+PERMITTED_USER="uni_adm,eddturner"
+
+# ======= check the right user runs this script =======================================
+if ! echo "$PERMITTED_USER" | grep "$USER" > /dev/null 2>&1; then
     echo "This service can only be run as user, 'uni_adm'";
     exit 1;
 fi;
 
-if [ ! -f "environment.variables" ]; then
+
+# ======= read the variables used by the control scripts =======================================
+source "environment.variables" || {
     echo "Please create a file called, environment.variables, containing the necessary environment variables."
     exit 1;
-fi
-source "environment.variables"
+}
 
+[ ! -z "$ARTIFACT_GROUP" ] || [ ! -z "$ARTIFACT_VERSION" ] || [[ ! -z "$ARTIFACT_ID" ]] || {
+    echo "Please specify the environment variables ARTIFACT_GROUP, ARTIFACT_VERSION and ARTIFACT_ID, in file, \
+environment.variables."
+    exit 1
+}
+
+# ======= CONSTANTS =======================================
 RUN_DIR="$SERVICE_PATH/out"
 LIB_DIR="$SERVICE_PATH/lib"
 PIDFILE="$RUN_DIR/run.pid"
-SERVICE_JAR="$JAR"
+SERVICE_JAR="$ARTIFACT_ID-$ARTIFACT_VERSION.jar"
 SERVER_ADDR_BINDING="-Dserver.address=0.0.0.0"
 
+# ======= build java variables =======================================
+if [ -z "$JAVA_HOME" ]; then
+    echo "JAVA_HOME environment variable must be set. Aborting."
+    exit 1;
+fi
+JAVA=$JAVA_HOME/bin/java
+
+JVM_MEM_MAX="-Xms1024M"
+JVM_MEM_MIN="-Xmx3096M"
+JAVA_OPTS="-Dcom.sun.management.jmxremote  \
+            -Dcom.sun.management.jmxremote.authenticate=false \
+            -Dcom.sun.management.jmxremote.ssl=false  \
+            -Dcom.sun.management.jmxremote.port=$JXM_REMOTE_PORT"
+
+if [ "$JVM_FLIGHT_RECORDER" == "on" ]; then
+    JAVA_OPTS="$JAVA_OPTS \
+            -XX:+UnlockCommercialFeatures \
+            -XX:+FlightRecorder \
+            -XX:FlightRecorderOptions=loglevel=debug"
+fi
+
+# ======= build the command to start the service =======================================
+RUN_COMMAND="$JAVA $JVM_MEM_MIN $JVM_MEM_MAX $JAVA_OPTS -jar -Dserver.port=$PORT $SERVER_ADDR_BINDING $LIB_DIR/$SERVICE_JAR"
+
+# ======= bail if the service has already been started =======================================
 if [ -e $PIDFILE ]
 then
     echo "Service has already been started: $(cat $PIDFILE)"
     exit 1
 fi
 
-# save current directory
+# ======= save current directory =======================================
 pushd . > /dev/null
 
-cd $LIB_DIR
 
+# ======= check the service jar exists before proceeding ... =======================================
+cd $LIB_DIR
 ls -1 $SERVICE_JAR > /dev/null 2>&1
 if [ ! $? ]; then
     echo "Error: $LIB_DIR/$SERVICE_JAR does not exist. Aborting."
@@ -40,43 +81,26 @@ fi
 
 if [ ! -e "$RUN_DIR" ]; then
     mkdir -p $RUN_DIR
+    echo "Created base directory '$RUN_DIR' for recording activities of the live application, e.g., logs"
 fi
 
+
+# ======= start the application and record the PID =======================================
 cd $RUN_DIR
-
-if [ -z "$JAVA_HOME" ]; then
-    echo "JAVA_HOME environment variable must be set. Aborting."
-    exit 1;
-fi
-
-JAVA=$JAVA_HOME/bin/java
-JVM_MEM_MAX="-Xms1024M"
-JVM_MEM_MIN="-Xmx3096M"
-JAVA_OPTS="-Dcom.sun.management.jmxremote  \
-            -Dcom.sun.management.jmxremote.authenticate=false \
-            -Dcom.sun.management.jmxremote.ssl=false  \
-            -Dcom.sun.management.jmxremote.port=$JXM_REMOTE_PORT"
-JAVA_OPTS="$JAVA_OPTS \
-            -XX:+UnlockCommercialFeatures \
-            -XX:+FlightRecorder \
-            -XX:FlightRecorderOptions=loglevel=debug"
-
-RUN_COMMAND="$JAVA $JVM_MEM_MIN $JVM_MEM_MAX $JAVA_OPTS -jar -Dserver.port=$PORT $SERVER_ADDR_BINDING $LIB_DIR/$SERVICE_JAR"
-
-echo "Running: $RUN_COMMAND"
+echo "Running command: $RUN_COMMAND"
 
 # run the application headless
-#nohup $RUN_COMMAND > /dev/null 2>&1 &
-nohup $RUN_COMMAND &
+nohup $RUN_COMMAND > /dev/null 2>&1 &
 PID="$!"
 
-echo "Acquiring PID"
+echo "Sleeping 2 seconds, before acquiring PID"
 sleep 2
 ps $PID > /dev/null || {
     echo "The process could not be started. Please check."
     exit 1
 }
 
+echo "PID retrieved successfully"
 echo "$PID $(hostname)" > $PIDFILE
 
 # jump back to current directory
