added update script. needs tidying, + tidying start and stop

diff --git a/ontology-rest/src/main/bin/start b/ontology-rest/src/main/bin/start
--- a/ontology-rest/src/main/bin/start
+++ b/ontology-rest/src/main/bin/start
@@ -4,7 +4,7 @@ set -euo pipefail
 IFS=$'\n\t '
 
 # check the right user runs this
-if [ $USER != "edd" ] ; then
+if [ $USER != "eddturner" ] ; then
     echo "This service can only be run as user, 'uni_adm'";
     exit 1;
 fi;
@@ -15,8 +15,11 @@ if [ ! -f "environment.variables" ]; then
 fi
 source "environment.variables"
 
-PIDFILE="$SERVICE_PATH/run.pid"
+RUN_DIR="$SERVICE_PATH/out"
+LIB_DIR="$SERVICE_PATH/lib"
+PIDFILE="$RUN_DIR/run.pid"
 SERVICE_JAR="$JAR"
+SERVER_ADDR_BINDING="-Dserver.address=0.0.0.0"
 
 if [ -e $PIDFILE ]
 then
@@ -27,13 +30,19 @@ fi
 # save current directory
 pushd . > /dev/null
 
-cd $SERVICE_PATH
+cd $LIB_DIR
 
 ls -1 $SERVICE_JAR > /dev/null 2>&1
 if [ ! $? ]; then
-    echo "Error: $SERVICE_PATH/$SERVICE_JAR does not exist. Aborting."
+    echo "Error: $LIB_DIR/$SERVICE_JAR does not exist. Aborting."
     exit 1
 fi
+
+if [ ! -e "$RUN_DIR" ]; then
+    mkdir -p $RUN_DIR
+fi
+
+cd $RUN_DIR
 
 if [ -z "$JAVA_HOME" ]; then
     echo "JAVA_HOME environment variable must be set. Aborting."
@@ -46,19 +55,28 @@ JVM_MEM_MIN="-Xmx3096M"
 JAVA_OPTS="-Dcom.sun.management.jmxremote  \
             -Dcom.sun.management.jmxremote.authenticate=false \
             -Dcom.sun.management.jmxremote.ssl=false  \
-            -Dcom.sun.management.jmxremote.port=9091"
+            -Dcom.sun.management.jmxremote.port=$JXM_REMOTE_PORT"
 JAVA_OPTS="$JAVA_OPTS \
             -XX:+UnlockCommercialFeatures \
             -XX:+FlightRecorder \
             -XX:FlightRecorderOptions=loglevel=debug"
 
-RUN_COMMAND="$JAVA $JVM_MEM_MIN $JVM_MEM_MAX $JAVA_OPTS -jar -Dserver.port=$PORT $SERVICE_JAR"
+RUN_COMMAND="$JAVA $JVM_MEM_MIN $JVM_MEM_MAX $JAVA_OPTS -jar -Dserver.port=$PORT $SERVER_ADDR_BINDING $LIB_DIR/$SERVICE_JAR"
 
 echo "Running: $RUN_COMMAND"
+
 # run the application headless
 #nohup $RUN_COMMAND > /dev/null 2>&1 &
 nohup $RUN_COMMAND &
 PID="$!"
+
+echo "Acquiring PID"
+sleep 2
+ps $PID > /dev/null || {
+    echo "The process could not be started. Please check."
+    exit 1
+}
+
 echo "$PID $(hostname)" > $PIDFILE
 
 # jump back to current directory
diff --git a/ontology-rest/src/main/bin/update b/ontology-rest/src/main/bin/update
--- a/ontology-rest/src/main/bin/update
+++ b/ontology-rest/src/main/bin/update
@@ -1,3 +1,101 @@
 #! /bin/bash
 
+set -euo pipefail
+IFS=$'\n\t '
+
+# take a string and add a time-stamp to it
+function addTimeStamp() {
+    local dirname="$(dirname $1)"
+    local fname=$(basename "$1")
+    local fext=""
+    if echo "$fname" | grep '\.'; then
+        fext=".${fname##*.}"
+    fi
+    local fname="${fname%.*}"
+    echo "$dirname/$fname-$(date '+%d-%m-%Y--%H:%M:%S')$fext"
+}
+
 # Fetches latest library and stores it in lib
+
+source "environment.variables" || {
+    echo "Please create a file called, environment.variables, containing the necessary environment variables."
+    exit 1;
+}
+
+[ ! -z "$ARTIFACT_GROUP" ] || [ ! -z "$ARTIFACT_VERSION" ] || [[ ! -z "$ARTIFACT_ID" ]] || {
+    echo "Please specify the environment variables ARTIFACT_GROUP, ARTIFACT_VERSION and ARTIFACT_ID, in file, \
+environment.variables."
+    exit 1
+}
+
+LIB_DIR="$SERVICE_PATH/lib"
+BACKUP_LIB_DIR="$SERVICE_PATH/lib/backups"
+
+if [ ! -d "$LIB_DIR" ]; then
+    mkdir $LIB_DIR
+fi
+if [ ! -d "$BACKUP_LIB_DIR" ]; then
+    mkdir $BACKUP_LIB_DIR
+fi
+
+JAR_NAME="$ARTIFACT_ID-$ARTIFACT_VERSION.jar"
+JAR_NAME_TEMP="$(addTimeStamp $JAR_NAME)"
+TEMP_DIR="$(addTimeStamp 'temp')"
+TIMESTAMP_DIR="$(addTimeStamp $BACKUP_LIB_DIR/version)"
+
+if [ ! -d "$TIMESTAMP_DIR" ]; then
+    mkdir $TIMESTAMP_DIR
+fi
+
+
+GROUP_AS_URL="$(echo $ARTIFACT_GROUP | sed -e 's/\./\//g')"
+
+ARTIFACT_URL="$GROUP_AS_URL/$ARTIFACT_ID/$ARTIFACT_VERSION/$JAR_NAME"
+
+# repository info
+REPO_TYPE="release"
+REPO_NAME="uniprot-artifactory-release"
+if echo "$JAR_NAME" | grep 'SNAPSHOT' > /dev/null; then
+    REPO_TYPE="snapshot"
+    REPO_NAME="uniprot-artifactory-snapshots"
+fi
+
+REPO_URL="http://wwwdev.ebi.ac.uk/uniprot/artifactory/$REPO_TYPE"
+ARTIFACT_URL="http://wwwdev.ebi.ac.uk/uniprot/artifactory/$REPO_TYPE/$ARTIFACT_URL"
+
+# fetch the artifact and store in lib dir
+echo "Fetching $ARTIFACT_URL"
+
+GAV="$ARTIFACT_GROUP:$ARTIFACT_ID:$ARTIFACT_VERSION"
+
+# get the artifact
+mvn org.apache.maven.plugins:maven-dependency-plugin:2.7:copy \
+        -DrepoUrl="$REPO_URL" \
+        -DrepoId="$REPO_NAME" \
+        -Dartifact="$GAV" \
+        -Dtype=jar \
+        -DoutputDirectory="$TEMP_DIR"
+
+for lib in "$(ls $LIB_DIR/*.jar)"; do
+#    echo "--- $lib"
+    ls "$lib" > /dev/null 2>&1 && mv "$lib" "$TIMESTAMP_DIR"
+done
+
+pushd . > /dev/null
+cd "$BACKUP_LIB_DIR"
+# double check we're actually in the backup directory, before deleting anything!
+if [ "$(basename $(pwd))" == "$(basename $BACKUP_LIB_DIR)" ]; then
+    echo "Deleting oldest backups, but keeping newest 5";
+    (ls -t|head -n 5;ls)|sort|uniq -u|xargs rm -rf;
+fi
+popd > /dev/null
+
+for new_lib in "$(ls $TEMP_DIR/*.jar)"; do
+#    echo "--- moving new_lib"
+    ls "$new_lib" > /dev/null 2>&1 && mv "$new_lib" "$LIB_DIR"
+done
+rmdir $TEMP_DIR || {
+    echo "Could not clean up temp directory: '$TEMP_DIR'. Please check it is empty."
+}
+
+echo "done"
